-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '3276cddd1c7e58ac' HASH '2f8487315a4d5032636250ad4c8872ab1f8705f3e7eb11621da634184ff63902' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."AUTHOR"(
    "AUTHOR_ID" UUID NOT NULL,
    "AUTHOR_FULL_NAME" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."AUTHOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("AUTHOR_ID");
CREATE CACHED TABLE "PUBLIC"."BOOK"(
    "BOOK_PAGES_COUNT" INTEGER,
    "BOOK_READ_FINISH_DATE" DATE,
    "BOOK_READ_START_DATE" DATE,
    "BOOK_AUTHOR_ID" UUID NOT NULL,
    "BOOK_ID" UUID NOT NULL,
    "BOOK_DESCRIPTION" CHARACTER VARYING,
    "BOOK_NAME" CHARACTER VARYING(255),
    "BOOK_REVIEW" CHARACTER VARYING,
    "BOOK_BOOK_FILE_ID" UUID,
    "BOOK_RATING_TYPE_ID" UUID
);    
ALTER TABLE "PUBLIC"."BOOK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("BOOK_ID");    
CREATE FORCE VIEW "PUBLIC"."V_AUTHOR_BOOK_COUNT"("AUTHOR_ID", "AUTHOR_BOOK_COUNT") AS
SELECT
    "AUTHOR"."AUTHOR_ID",
    COALESCE("BOOK_COUNT"."CNT", 0) AS "AUTHOR_BOOK_COUNT"
FROM "PUBLIC"."AUTHOR"
LEFT OUTER JOIN (
    SELECT
        "BOOK_AUTHOR_ID" AS "AUTHOR_ID",
        COUNT(*) AS "CNT"
    FROM "PUBLIC"."BOOK"
    GROUP BY "BOOK_AUTHOR_ID"
) "BOOK_COUNT"
    ON "BOOK_COUNT"."AUTHOR_ID" = "AUTHOR"."AUTHOR_ID";            
CREATE CACHED TABLE "PUBLIC"."BOOK_FILE_BLOB"(
    "BOOK_FILE_BLOB_ID" UUID NOT NULL,
    "BOOK_FILE_BLOB" BINARY LARGE OBJECT
);          
ALTER TABLE "PUBLIC"."BOOK_FILE_BLOB" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("BOOK_FILE_BLOB_ID");
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.BOOK_FILE_BLOB;          
CREATE CACHED TABLE "PUBLIC"."RATING_TYPE"(
    "RATING_TYPE_ID" UUID NOT NULL,
    "RATING_TYPE_NAME" CHARACTER VARYING(255),
    "RATING_TYPE_ORDER" INTEGER
);         
ALTER TABLE "PUBLIC"."RATING_TYPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("RATING_TYPE_ID");      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.RATING_TYPE;             
CREATE CACHED TABLE "PUBLIC"."BOOK_FILE"(
    "BOOK_FILE_ID" UUID NOT NULL,
    "BOOK_FILE_ORIGINAL_NAME" CHARACTER VARYING(255),
    "BOOK_FILE_BLOB_ID" UUID NOT NULL
);     
ALTER TABLE "PUBLIC"."BOOK_FILE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("BOOK_FILE_ID");          
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.BOOK_FILE;               
ALTER TABLE "PUBLIC"."BOOK" ADD CONSTRAINT "PUBLIC"."UKB4E8P3UX52HS6J5T2PISQV9S6" UNIQUE NULLS DISTINCT ("BOOK_BOOK_FILE_ID");
ALTER TABLE "PUBLIC"."BOOK_FILE" ADD CONSTRAINT "PUBLIC"."UKDBY21CBVYCVBB95OVNPJRD6QL" UNIQUE NULLS DISTINCT ("BOOK_FILE_BLOB_ID");           
ALTER TABLE "PUBLIC"."BOOK" ADD CONSTRAINT "PUBLIC"."FK7M19CTFD2T5ACT0332CDXHANP" FOREIGN KEY("BOOK_AUTHOR_ID") REFERENCES "PUBLIC"."AUTHOR"("AUTHOR_ID") NOCHECK;            
ALTER TABLE "PUBLIC"."BOOK" ADD CONSTRAINT "PUBLIC"."FKJWIV6YLIESO1NMFRCMAT4KA3E" FOREIGN KEY("BOOK_RATING_TYPE_ID") REFERENCES "PUBLIC"."RATING_TYPE"("RATING_TYPE_ID") NOCHECK;             
ALTER TABLE "PUBLIC"."BOOK" ADD CONSTRAINT "PUBLIC"."FKCX53D1CD06OLXSR8L5EBMXA2Q" FOREIGN KEY("BOOK_BOOK_FILE_ID") REFERENCES "PUBLIC"."BOOK_FILE"("BOOK_FILE_ID") NOCHECK;   
ALTER TABLE "PUBLIC"."BOOK_FILE" ADD CONSTRAINT "PUBLIC"."FKSWL2CHPMK7SPCEAMMT83T863J" FOREIGN KEY("BOOK_FILE_BLOB_ID") REFERENCES "PUBLIC"."BOOK_FILE_BLOB"("BOOK_FILE_BLOB_ID") NOCHECK;    

INSERT INTO "PUBLIC"."RATING_TYPE" VALUES
(UUID 'd8d1b2bb-32af-4afd-8cf7-078681ca87c6', U&'\041f\043b\043e\0445\043e', 1),
(UUID 'c7a62116-99d8-42a0-96a7-3e7f53faa136', U&'\041d\043e\0440\043c', 2),
(UUID '6baeaf12-d59c-460b-9645-cc72cef9b3d5', U&'\041b\044e\0431\0438\043c\043e\0435', 3);